import { ClerkProvider } from "@clerk/nextjs"
import { Raleway } from "next/font/google"
import { Header } from "@/components/server/header"
import "../styles/globals.css"

import { TrpcProvider } from "../components/client/trpc-client"

const font = Raleway({
  subsets: ["latin"],
})

export const metadata = {
  title: "Surveyist",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <TrpcProvider>
        <html lang="en" className={font.className}>
          <body>
            <Header />
            {children}
          </body>
        </html>
      </TrpcProvider>
    </ClerkProvider>
  )
}
